add callbacks nodes to channels
mhcomm/pypeman pull request #189
Opened 2022-11-25 15:30 UTC by quentinql

2022-11-28 08:15 UTC, feenes commented on pypeman/channels.py
> +        self.done_callback = None
please explain exactly when a callback will be called and whether they are mutually exclusive or whether it is possible that two or more callbacks can be called for the same node under certain circumstances.

2022-11-28 08:16 UTC, feenes commented on pypeman/channels.py
> +        self.reject_callback = None  # TODO: maybe add a 'default' callback that is launch everytime (may be useful for file cleaning for example)
that is lauched. Also comment is difinetely too long. so put it above the line

2022-11-28 08:17 UTC, feenes commented on pypeman/channels.py
> +                    await self.fail_callback[0].handle(msg)
so a rejection is a fail?

2022-11-28 08:19 UTC, feenes commented on pypeman/channels.py
> +    def _init_callback_nodes(self, *callback_nodes):
doc string missing.

2022-11-28 08:21 UTC, feenes commented on pypeman/channels.py
> +            node.channel = self
How can a function that is called init_callback_nodes() change channels of existing nodes?

2022-11-28 08:22 UTC, feenes commented on pypeman/channels.py
> +            previous_node = callback_nodes[0]
`> 1` or `> 0`

2022-11-28 08:26 UTC, feenes commented on pypeman/channels.py
> +        return callback_nodes
function name seems a little confusing.
it seems to do many things and not all are related to callbacks. but perhaps I'm missing some context

2022-11-28 08:27 UTC, feenes commented on pypeman/channels.py
> +        Add a callback when channel raise an exception (except Dropped)
raises

2022-11-28 08:30 UTC, feenes commented on pypeman/tests/test_channel.py
> +        """ Whether BaseChannel done_callback is working """
you should also checked that it is not called in the cases where it should not be called.

2022-11-28 08:37 UTC, feenes commented on pypeman/channels.py
> +        self.done_callback = None
also document call order if multiple callbacks can be called

2022-11-28 08:44 UTC, feenes commented on pypeman/channels.py
> +        Add a callback when channel ends correctly (and without raising Dropped)
language is wrong.

We always add the callback.

perhaps something shorter to find but what's correct is:

"Add a callback, that will be called, when ...."

2022-11-28 08:45 UTC, feenes commented on pypeman/tests/test_channel.py
> +def raise_dropped(msg):
doc string:
show how and why this function would be used instead of directly raising the exception.

2022-11-28 08:47 UTC, feenes requested changes
some minor feedback.

mostly documentation

2022-12-01 10:51 UTC, quentinql commented on pypeman/channels.py
> +        entrymsg = ctx.get(MSG_CTXVAR)
reset()

2022-12-01 15:23 UTC, quentinql commented on pypeman/channels.py
> +        # TODO: maybe add a 'default' callback that is launch everytime
final_callback

2022-12-01 15:23 UTC, quentinql commented on pypeman/channels.py
> +        self.done_callback = None
ok_callback

2023-01-12 09:02 UTC, feenes approved these changes

2023-01-12 09:02 UTC, merged